In [1]:
import pandas as pd

In [2]:
import sqlite3 as sql

In [3]:
conn=sql.connect('factbook.db')

In [4]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [5]:
q='select * from sqlite_master'
q

'select * from sqlite_master'

In [6]:
sql_query(q)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

## List all cities where the area is greater than 5000, along with their population.

In [14]:
q = '''select cities.name, cities.population
from cities
join facts on cities.facts_id = facts.id
WHERE facts.area > 5000'''
sql_query(q)

          name  population
0    Abu Dhabi      942000
1        Dubai     1978000
2      Sharjah      983000
3        Kabul     3097000
4      Algiers     2916000
..         ...         ...
349    Mbabane       66000
350      Sanaa     2419000
351       Aden      784000
352     Lusaka     1802000
353     Harare     1542000

[354 rows x 2 columns]

## 2. List the names of capital cities where the death rate is greater than 2% and the birth rate is less than 20%

In [15]:
q = '''
select cities.name
from cities
join facts on cities.facts_id = facts.id
where cities.capital = 1
and facts.death_rate > 2
and facts.birth_rate < 20
'''
sql_query(q)

                 name
0          Oranjestad
1        Saint John'S
2                Baku
3              Tirana
4             Yerevan
..                ...
123         Road Town
124             Hanoi
125  Charlotte Amalie
126          Windhoek
127          Mata-Utu

[128 rows x 1 columns]

## 3. List the cities with a population growth rate between 1% and 5%, sorted in desc by population growth.

In [24]:
q = '''
select cities.name, facts.population_growth
from cities
join facts on cities.facts_id = facts.id
where facts.population_growth between 1 and 5
order by facts.population_growth DESC
'''
sql_query(q)

          name  population_growth
0         Juba               4.02
1     Lilongwe               3.32
2    Bujumbura               3.28
3       Niamey               3.25
4      Kampala               3.24
..         ...                ...
210        Fes               1.00
211  Marrakech               1.00
212    Tangier               1.00
213     Agadir               1.00
214    Managua               1.00

[215 rows x 2 columns]

## 4. Find countries that start with &quot;A&quot; and do not have any cities listed in the cities table. The query should return the country name and city name. Using left join

In [26]:
q = '''
select facts.name as country_name, cities.name as city_name
from facts
left join cities on facts.id = cities.facts_id
where facts.name Like 'A%'
and cities.id is null
'''

sql_query(q)

                  country_name city_name
0  Ashmore and Cartier Islands      None
1                     Akrotiri      None
2                   Antarctica      None
3                 Arctic Ocean      None
4               Atlantic Ocean      None

## 5. List all capital cities and their corresponding death rate using a LEFT JOIN.

In [27]:
q = '''
select cities.name, facts.death_rate
from cities
left join facts on cities.facts_id = facts.id
where cities.capital = 1
'''
sql_query(q)

             name  death_rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]